# Generated by Django 4.1.5 on 2023-02-16 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0003_sentence_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentence',
            name='image_url',
            field=models.URLField(blank=True, default='https://picsum.photos/id/237/200/300'),
        ),
    ]
