# Generated by Django 4.1.5 on 2023-03-08 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0006_remove_imageselection_optional_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='set',
            name='text',
            field=models.CharField(default='Default text value', max_length=520),
            preserve_default=False,
        ),
    ]
