# Generated by Django 4.1.5 on 2023-03-09 01:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0007_set_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageselection',
            name='parent_sentence',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='editor.sentence'),
            preserve_default=False,
        ),
    ]
