# Generated by Django 4.1.5 on 2023-03-09 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0009_alter_imageselection_parent_sentence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentence',
            name='image_url',
            field=models.URLField(blank=True, default='https://picsum.photos/id/237/200/300', max_length=520),
        ),
    ]
