# Generated by Django 4.1.5 on 2023-03-18 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0010_alter_sentence_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedimage',
            name='selected',
            field=models.BooleanField(default=False),
        ),
    ]
