# Generated by Django 4.1.5 on 2023-04-01 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0012_set_created_by_set_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentence',
            name='sound_clip',
            field=models.CharField(default='https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3', max_length=520),
            preserve_default=False,
        ),
    ]
