# Generated by Django 4.1.5 on 2023-04-13 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0013_sentence_sound_clip'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageselection',
            name='ai_generated',
            field=models.BooleanField(default=True),
        ),
    ]
